### ISSUE TITLE
How do i use switch images in dark mode

### ISSUE THREAD

**Issue by avradip** [zeon-studio/hugoplate#47]
Can I use two banner images , one for regular mode and another for dark mode? Similar image switching like the logo

**Comment by tfsomrat** [comment]
Hey @avradip, thanks for your interest. Yes, you can do it. You can do whatever you want because it's a starter template. You just need to know how to do it.

You can check the logo code and implement it on another component, or you can take our theme customization service from https://zeon.studio/contact
