### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by eqslab** [zeon-studio/hugoplate#94]
Hello guys! Could you please verify the correctness of config file for **GitHub Actions**?

I got an error trying to build a website. Sounds like it could be a problem with `postcss-cli`, but my attempts to solve the issue weren't successful. Will be very helpful for the help. Thank you!

![2024-02-13_01-27_1](https://github.com/zeon-studio/hugoplate/assets/157070559/7086bf79-caeb-45fa-b8d8-b58c0c1e5e34)
![2024-02-13_01-27](https://github.com/zeon-studio/hugoplate/assets/157070559/1f2fbded-f5b8-4863-a17f-f5b2396c4838)

**Comment by arijitlaik** [comment]
Honestly, bit difficult to say what exactly went wrong for this use case, since the ci builds were successful with the pr #86 , here was my last build using this updated action, maybe @eqslab can revert to the older actions and see if things are running smoothly
![Screenshot from 2024-02-13 11-51-00](https://github.com/zeon-studio/hugoplate/assets/10157121/f82a8240-a9e9-4708-9bb4-e526388ea1fe)

**Comment by embedded-consultants** [comment]
Fixed it by `  NODE_VERSION: "20.0.0"` in the .github main.yml file.

**Comment by eqslab** [comment]
> Fixed it by ` NODE_VERSION: "20.0.0"` in the .github main.yml file.

It worked out for me! A big, big thank you!

**Comment by tfsomrat** [comment]
I have updated the node version in main.yml file. thanks to @embedded-consultants
